[package]
name = "job_scheduler"
version = "1.2.1"
authors = ["Lori Holden <noreply@loriholden.com>"]
description = "A simple cron-like job scheduling library for Rust."

documentation = "https://docs.rs/job_scheduler/"
repository = "https://github.com/lholden/job_scheduler"

license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["cron", "crontab", "scheduler", "job"]

categories = ["date-and-time"]

edition = "2021"

[dependencies]
cron = "~0.11"
chrono = { version = "~0.4", default-features = false, features = ["clock"] }
uuid = { version = "~1.0", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "time", "rt-multi-thread"] }
